# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='competitor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_medical',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='mail',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='mail_father',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='mail_mother',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='mobile_phone_father',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='mobile_phone_mother',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
