# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManager', '0002_auto_20161228_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
