# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManager', '0004_athlete_mobile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalWarnState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_months_warning', models.BooleanField()),
                ('week_warning', models.BooleanField()),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_warn_state', to='TeamManager.Athlete')),
            ],
        ),
    ]
