# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManager', '0005_medicalwarnstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalwarnstate',
            old_name='three_months_warning',
            new_name='first_warning',
        ),
        migrations.RenameField(
            model_name='medicalwarnstate',
            old_name='week_warning',
            new_name='second_warning',
        ),
    ]
