# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminBackend', '0002_auto_20170501_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_mail_title', models.CharField(max_length=150)),
                ('medical_mail_text', models.TextField()),
            ],
        ),
    ]
