# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminBackend', '0003_mailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='medical_mail_cc',
            field=models.EmailField(default='xyz@xyz.de', max_length=254),
            preserve_default=False,
        ),
    ]
