# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminBackend', '0005_generalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='email_security',
            field=models.CharField(choices=[('NO', 'None'), ('TLS', 'TLS'), ('SSL', 'SSL')], default='NO', max_length=3),
        ),
    ]
